version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "$PWD/selenoid:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/selenoid:/opt/selenoid/video"
      - "$PWD/selenoid:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD
    command: ["-conf", "/etc/selenoid/browsers.json",
"-video-output-dir", "/opt/selenoid/video", "-log-output-dir",
"/opt/selenoid/logs", "-service-startup-timeout", "5m0s"]
    ports:
      - "4444:4444"
  selenoid-ui:
    network_mode: bridge
    links:
      - selenoid
    image: aerokube/selenoid-ui
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]